services:
  nginx:
    container_name: nginx
    depends_on:
      - magento
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      - frontend

  db:
    image: mysql:8.0
    container_name: db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 40s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "magento"
      MYSQL_USER: "magento"
      MYSQL_PASSWORD: "magento"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:7.17.23
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend

  magento:
    container_name: magento
    image: digidanieltech/magento2ce:php8.2-fpm-bookworm
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      # Required
      MAGENTO_VERSION: 2.4.6
      MAGENTO_PUBLIC_KEY: ${MAGENTO_PUBLIC_KEY} # Loaded from environment variable for security
      MAGENTO_SECRET_KEY: ${MAGENTO_SECRET_KEY} # Loaded from environment variable for security

      # Magento base configuration
      MAGENTO_BASE_URL: "https://localhost/"
      # LANGUAGE: "en_US"
      # CURRENCY: "USD"
      # TIMEZONE: "America/Chicago"
      # USE_REWRITES: "1"

      # Database configuration
      DB_HOST: "db"
      # DB_NAME: "magento"
      # DB_USER: "magento"
      # DB_PASS: "magento"

      # Admin configuration
      # ADMIN_FIRSTNAME: "admin"
      # ADMIN_LASTNAME: "admin"
      # ADMIN_EMAIL: "admin@admin.com"
      # ADMIN_USER: "admin"
      # ADMIN_PASSWORD: "admin123"

      # Search engine configuration
      SEARCH_ENGINE_HOST: "elasticsearch"
      # SEARCH_ENGINE_HOST: "localhost"
      # SEARCH_ENGINE_PORT: "9200"
      # SEARCH_ENGINE_INDEX_PREFIX: "magento2"
      # SEARCH_ENGINE_TIMEOUT: "15"
      # SEARCH_ENGINE_ENABLE_AUTH: "0"
      # SEARCH_ENGINE_USERNAME: ""
      # SEARCH_ENGINE_PASSWORD: ""
    env_file:
      - .env
    networks:
      - backend

volumes:
  db_data:
  es_data:

networks:
  frontend:
  backend:
